### ISSUE TITLE
Column overrides whenever adding a new feature

### ISSUE THREAD

**Issue by ronenschmitz** [desertwolf7/NumericalDigitize#2] opened 2020-07-28 17:00 UTC
Say you have a shapefile layer in QGIS that contains data in the different columns of your shapefile.
Whenever I add a new feature with this plugin in that shapefile layer, and provide data for the different columns, it will spread the new data into all other features – which of course ends up in a mess. 
Any clue to that?

Thank you!

**Comment by desertwolf7** [comment] 2020-08-17 14:10
I can't reproduce exactly this bug. When adding features in new created shape file it's overriding columns only of first created record. Other records keep original values. 
Bug fixed in new release 0.4.5.

**Closed as completed** 2021-04-04 15:37 UTC
